<template>
  <div class="all">
     <div class="top">
      <el-input
        placeholder="输入检索的关键字"
        size="medium"
        v-model="searchForm.contentName"
        @keyup.enter.native="search"
      >
        <template #suffix>
          <i class="el-icon-search el-input__icon" @click="getListTable(1)"/>
        </template>
      </el-input>
    </div>
    <div class="mid">
      <el-table
      :data="currentTabelData"
      border
      style="width: 100%">
      <el-table-column
        fixed
        prop="id"
        label="公司编号"
        width="150">
      </el-table-column>
      <el-table-column
        prop="info"
        label="来源"
        width="120">
      </el-table-column>
      <el-table-column
        prop="品种"
        label="品种"
        width="120">
      </el-table-column>
      <el-table-column
        prop="组织状态"
        label="组织状态"
        width="150">
      </el-table-column>
      <el-table-column
        prop="色泽"
        label="色泽"
        width="120">
      </el-table-column>
      <el-table-column
        prop="水分"
        label="水分"
        width="120">
      </el-table-column>
      <el-table-column
        prop="蛋白质"
        label="蛋白质"
        width="120">
      </el-table-column>
      <el-table-column
        prop="脂肪"
        label="脂肪"
        width="120">
      </el-table-column>
      <el-table-column
        prop="乳糖"
        label="乳糖"
        width="120">
      </el-table-column>
      <el-table-column
        prop="蔗糖"
        label="蔗糖"
        width="120">
      </el-table-column>
      <el-table-column
        prop="维生素A"
        label="维生素A"
        width="120">
      </el-table-column>
      <el-table-column
        prop="维生素D"
        label="维生素D"
        width="120">
      </el-table-column>
      <el-table-column
        prop="维生素E"
        label="维生素E"
        width="120">
      </el-table-column>
      <el-table-column
        prop="维生素K1"
        label="维生素K1"
        width="120">
      </el-table-column>
      <el-table-column
        prop="维生素B1"
        label="维生素B1"
        width="120">
      </el-table-column>
      <el-table-column
        prop="维生素B2"
        label="维生素B2"
        width="120">
      </el-table-column>
      <el-table-column
        prop="维生素B6"
        label="维生素B6"
        width="120">
      </el-table-column>
      <el-table-column
        prop="维生素B12"
        label="维生素B12"
        width="120">
      </el-table-column>
      <el-table-column
        prop="烟酸"
        label="烟酸"
        width="120">
      </el-table-column>
      <el-table-column
        prop="叶酸"
        label="叶酸"
        width="120">
      </el-table-column>
      <el-table-column
        prop="泛酸"
        label="泛酸"
        width="120">
      </el-table-column>
      <el-table-column
        prop="维生素C"
        label="维生素C"
        width="120">
      </el-table-column>
      <el-table-column
        prop="生物素"
        label="生物素"
        width="120">
      </el-table-column>
      <el-table-column
        prop="胆碱"
        label="胆碱"
        width="120">
      </el-table-column>
      <el-table-column
        prop="铁"
        label="铁"
        width="120">
      </el-table-column>
      <el-table-column
        prop="钙"
        label="钙"
        width="120">
      </el-table-column>
      <el-table-column
        prop="锌"
        label="锌"
        width="120">
      </el-table-column>
      <el-table-column
        prop="磷"
        label="磷"
        width="120">
      </el-table-column>
      <el-table-column
        prop="钠"
        label="钠"
        width="120">
      </el-table-column>
      <el-table-column
        prop="钾"
        label="钾"
        width="120">
      </el-table-column>
      <el-table-column
        prop="镁"
        label="镁"
        width="120">
      </el-table-column>
      <el-table-column
        prop="铜"
        label="铜"
        width="120">
      </el-table-column>
      <el-table-column
        prop="锰"
        label="锰"
        width="120">
      </el-table-column>
      <el-table-column
        prop="硒"
        label="硒"
        width="120">
      </el-table-column>
      <el-table-column
        prop="碘"
        label="碘"
        width="120">
      </el-table-column>
      <el-table-column
        prop="铅"
        label="铅"
        width="120">
      </el-table-column>
      <el-table-column
        prop="铬"
        label="铬"
        width="120">
      </el-table-column>
      <el-table-column
        prop="镉"
        label="镉"
        width="120">
      </el-table-column>
      <el-table-column
        prop="总砷"
        label="总砷"
        width="120">
      </el-table-column>
      <el-table-column
        prop="亚油酸"
        label="亚油酸"
        width="120">
      </el-table-column>
      <el-table-column
        prop="α-亚麻酸"
        label="α-亚麻酸"
        width="120">
      </el-table-column>
      <el-table-column
        prop="亚油酸:α-亚麻酸"
        label="亚油酸:α-亚麻酸"
        width="120">
      </el-table-column>
      <el-table-column
        prop="DHA"
        label="DHA"
        width="120">
      </el-table-column>
      <el-table-column
        prop="ARA"
        label="ARA"
        width="120">
      </el-table-column>
      <el-table-column
        prop="月桂酸和肉豆蔻酸占总脂肪酸的比例"
        label="月桂酸和肉豆蔻酸占总脂肪酸的比例"
        width="120">
      </el-table-column>
      <el-table-column
        prop="反式脂肪酸与总脂肪酸的比值"
        label="反式脂肪酸与总脂肪酸的比值"
        width="120">
      </el-table-column>
      <el-table-column
        prop="OPO"
        label="OPO"
        width="120">
      </el-table-column>
      <el-table-column
        prop="氯"
        label="氯"
        width="120">
      </el-table-column>
      <el-table-column
        prop="酸度"
        label="酸度"
        width="120">
      </el-table-column>
      <el-table-column
        prop="碳水化合物"
        label="碳水化合物"
        width="120">
      </el-table-column>
      <el-table-column
        prop="灰分"
        label="灰分"
        width="120">
      </el-table-column>
      <el-table-column
        prop="Asp"
        label="天冬氨酸"
        width="220">
      </el-table-column>
      <el-table-column
        prop="Thr"
        label="苏氨酸"
        width="120">
      </el-table-column>
      <el-table-column
        prop="Ser"
        label="丝氨酸"
        width="120">
      </el-table-column>
      <el-table-column
        prop="Glu"
        label="谷氨酸"
        width="120">
      </el-table-column>
      <el-table-column
        prop="Gly"
        label="甘氨酸"
        width="120">
      </el-table-column>
      <el-table-column
        prop="Ala"
        label="丙氨酸"
        width="120">
      </el-table-column>
      <el-table-column
        prop="Val"
        label="缬氨酸"
        width="120">
      </el-table-column>
      <el-table-column
        prop="Met"
        label="甲硫氨酸"
        width="120">
      </el-table-column>
      <el-table-column
        prop="Ile"
        label="异亮氨酸"
        width="120">
      </el-table-column>
      <el-table-column
        prop="Leu"
        label="亮氨酸"
        width="120">
      </el-table-column>
      <el-table-column
        prop="Tyr"
        label="酪氨酸"
        width="120">
      </el-table-column>
      <el-table-column
        prop="Phe"
        label="苯丙氨酸"
        width="120">
      </el-table-column>
      <el-table-column
        prop="Lys"
        label="赖氨酸"
        width="120">
      </el-table-column>
      <el-table-column
        prop="His"
        label="组氨酸"
        width="120">
      </el-table-column>
      <el-table-column
        prop="Arg"
        label="精氨酸"
        width="120">
      </el-table-column>
      <el-table-column
        prop="Pro"
        label="脯氨酸"
        width="120">
      </el-table-column>
      <el-table-column
        prop="氨基酸总量"
        label="氨基酸总量"
        width="120">
      </el-table-column>
      <el-table-column
        fixed="right"
        label="操作"
        width="100">
        <template slot-scope="scope">
          <el-button @click="edit(scope.row)" type="text" size="small">修改</el-button>
          <el-button @click="deletebrand(scope.row)" type="text" size="small">删除</el-button>
        </template>
      </el-table-column>
    </el-table>
    </div>
    <div class="footer">
      <el-pagination
        @size-change="handleSizeChange"
        @current-change="handleCurrentChange"
        :current-page="searchForm.pageIndex"
        :page-sizes="[15,30,45,60]"
        :page-size="searchForm.pageSize"
        layout="total, prev, pager, next, jumper"
        :total="totalCount"
      ></el-pagination>
    </div>
  </div>
</template>

<script>
//import { getQualitySafetyItems } from "@/services/index";
export default {
  data(){
    return{
      searchForm:{
        id: 1, //默认页码是第一页
        info: 15, //默认显示的条数
        品种: "东风日产" //关键字
      },
       totalCount: 0,
    };
  },
    methods:{
      //获取列表
    //   getListTable(){
    //     getQualitySafetyItems(this.searchForm).then(({data,totalCount})=>{
    //       this.tableData = data;
    //       this.totalCount = totalCount
    //     })
    //   },
       //搜索关键字
    search() {
      this.searchForm.pageIndex = 1; //初始化当前所在页数
      this.getListTable(); //获取数据
    },
       // 每条条数变化的回调处理
      handleSizeChange(val){
        // val变化后的每页的条数
        this.searchForm.pageSize = val;//更新每页的条数
        this.getListTable();//重新获取列表数据
      },
      // 页码变化的回调处理
      handleCurrentChange(val){
        //val 变化后的页码
        this.searchForm.pageIndex = val;
         this.getListTable();//重新获取列表数据
      }
  }
}
</script>
<style lang="scss" scoped>
.top {
    .el-button {
      font-size: 15px;
      margin: 30px 40px 20px 30px;
    }
.jk-table{
  color:#ccc
}
.footer {
    margin-top: 20px;
    text-align: right;
}
}
</style>